remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title: Thomas Weise
name: Thomas Weise
description: "The personal homepage of Prof. Dr. Thomas Weise."
url: https://thomasweise.github.io

# Site Author
author:
  name: "Thomas Weise"
  location: "Hefei, Anhui, China"
  email: tweise@hfuu.edu.cn
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:tweise@hfuu.edu.cn"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:tweise@ustc.edu.cn"

timezone: CST
