title: Thomas Weise

author:
  name: Thomas Weise
  email: tweise@hfuu.edu.cn

description: "The personal homepage of Prof. Dr. Thomas Weise."

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: contrast

date_format: "%Y-%m-%d"
