title: Thomas Weise (汤卫思) | Academic Homepage
author: Thomas Weise (汤卫思)
description: "The personal homepage of Prof. Dr. Thomas Weise (汤卫思)."

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

permalink: pretty
show_downloads: false
